### ISSUE TITLE
toHTML fail to convert a JSON field with null value

### ISSUE THREAD

**Issue by jcezardasilva** [createmeal/createmeal#38]
example:
the call toHTML({"html":null}) throw the exception:
TypeError: Cannot convert undefined or null to object

**Comment by MassiGy** [comment]
Hey there, 

Can you give us a link to the code, to be able to refer to it and help you as well.

Thanks

**Comment by comparesheriff** [comment]
I believe the method that is being called is this:
https://github.com/createmeal/createmeal/blob/a47c3e38aee99506e2da098b241028ee9e810302/src/index.js#L39

**Comment by marcelocesards** [comment]
Hi,

src/index.js calls NodeFacotory.getNode. Try to take a look in there.

 
Maybe is something in checking if the node is a self-closing tag " ​if​(​openTags​[​NodeFactory​.​isOpenTag​(​key​)​]​)  ", or after this on children generation. Self-closing tags should not have children.

Tanks in advance.

**Comment by PreetSangha** [comment]
I've submitted a PR https://github.com/createmeal/createmeal/pull/40 for this.

**Comment by marcelocesards** [comment]
Hi @PreetSangha, everithing is ok to me. 

there is something pending about the tests, you should adjust expected value in order to make it passes. But we have been refactoring all the tests, so I will accept it for now and generate a new issue to handler this in the future.

test as is:
assert.assert(createmeal.toHtml({"html":null}), "", "handles null");
result:
handles null FAILED! :( - 
expected: 
[] 
given: 
[<html></html>]!

to be:
assert.assert(createmeal.toHtml({"html":null}), "<html></html>", "handles null");
result: handles null: OK! :D

Thankyou very much!

**Comment by marcelocesards** [comment]
Hi @PreetSangha,

this test framework I have used, I created just for the porpouse of this project trying to avoid too much dependencies in te beggining of the project. It consists in three methods: 

- assert: test arguments to see if they corresponds with each other.
- failed: is called to say that first argument is different of seccond.
- success: if first is equals to seccond argument, this is called.

But, this is not the best practice, one time there are good solutions consolidated in the web. In this way, we have been substituing our own solution for the libs "mocha" and "chai". Mocha will test code and say if everything is ok or not. If something is wrong, it will throw the trace of the error and make easy to understand where is the problem. In addictional allows us to create test suites, running all tests in one shot.

Git flow determines but should be merged into master and enhancements into release. We have been working in release improvement for automation and soon we can define it better.

**Comment by PreetSangha** [comment]
Hi, thank you for explaining.

Do you think perhaps JEST might be a better option? It's pretty
lightweight and seems to be like yours but with more options?

regards,
Preet, in Auckland NZ

**Comment by jcezardasilva** [comment]
Hi, @PreetSangha,

Now our tests are already done in Mocha.
I will compare with JEST. Maybe in the future we can change.

regards,
Julio

**Comment by PreetSangha** [comment]
Thank you for explaining!

regards,
Preet, in Auckland NZ
